name: test

env:
  CI: true

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        version: 12.x
    - run: npm ci
    - run: npm test
    - run: npm run lint
